version: '3.8'
services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: Express
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      PATH: /opt/mssql-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    restart: unless-stopped
    ports:
      - '1433:1433'
    volumes:
      - type: volume
        source: db_data
        target: /var/opt/mssql

volumes:
  db_data:
